export const ARTIST_ROLES = [
  'SINGER',
  'WRITER',
  'COMPOSER',
  'PRODUCER',
  'FEATURED_ARTIST',
  'MUSIC_ARRANGER',
  'MIX_ENGINEER',
  'MASTER_ENGINEER',
  'GUITARIST',
  'BASSIST',
  'DRUMMER',
  'PIANIST',
  'TABLA_PLAYER',
  'FLUTE_PLAYER',
];
export const ARTIST_ROLE_LABELS = {
  SINGER: 'Singer',
  WRITER: 'Writer',
  COMPOSER: 'Composer',
  PRODUCER: 'Producer',
  FEATURED_ARTIST: 'Featured Artist',
  MUSIC_ARRANGER: 'Music Arranger',
  MIX_ENGINEER: 'Mix Engineer',
  MASTER_ENGINEER: 'Master Engineer',
  GUITARIST: 'Guitarist',
  BASSIST: 'Bassist',
  DRUMMER: 'Drummer',
  PIANIST: 'Pianist',
  TABLA_PLAYER: 'Tabla Player',
  FLUTE_PLAYER: 'Flute Player',
};